---
- hosts: all
  tasks:
    - name: install httpd
      yum: name=httpd state=latest
      become: true
      become_user: root

    - name: ensure apache is running
      service:
        name: httpd.service
        state: started
      become: yes
